name: swipewatch
description: "A new Flutter project."

publish_to: 'none' # This ensures the package won't be accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: 1.2.2
  flutter_dotenv: 5.2.1

  firebase_core: 3.10.0
  cloud_firestore: 5.6.1
  firebase_auth: 5.4.0

  flutter_swiper_null_safety: ^1.0.2
  card_swiper: ^2.0.4
  provider: 6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/movies_dataset.json
    - api_key.env
